#ifndef GODOT_PLATFORM_HAIKU_CONFIG_H
#define GODOT_PLATFORM_HAIKU_CONFIG_H

#define REAL_T_IS_DOUBLE 0
#define HAS_MKDIR
#define UNIX_ENABLED
#define HAIKU_ENABLED
#define THREADS_ENABLED
#define PTHREAD_ENABLED
#define OPENGL_ENABLED
#define GLES3_ENABLED

#endif
