#!/usr/bin/env python

Import("env")

sources = [
    "godot_haiku.cpp",
    "libgodot_haiku.cpp",
    "os_haiku.cpp",
    "display_server_haiku.cpp",
    "haiku_window.cpp",
    "haiku_gl_view.cpp",
    "gl_manager_haiku.cpp",
]

if env.get("HAIKU_AUDIO_ENABLED", False):
    sources.append("audio_driver_haiku.cpp")

objects = [env.Object("#platform/haiku/" + source) for source in sources]

if env.get("tools", False):
    export_sources = [
        "export/export_plugin.cpp",
        "export/export.cpp",
    ]
    objects += [env.Object("#platform/haiku/" + source) for source in export_sources]

if env["library_type"] == "static":
    env.add_library("#bin/libgodot", objects)
elif env["library_type"] == "shared":
    env.add_shared_library("#bin/libgodot", objects)
else:
    env.add_program("#bin/godot", objects)
